# Standards: 0.1
---
- name: Install required packages
  loop:
    - sudo
  package:
    name: "{{ item }}"
    state: present
  tags:
    - sudo

- name: Create defined group
  loop: "{{ sudo_groups }}"
  group:
    name: "{{ item }}"
    system: True
    state: present
  tags:
    - sudo

- name: Write sudoers config
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s
  tags:
    - sudo

...
