- name: os variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - sudo

- name: install packages
  when: sudo_install_package | default(True)
  loop:
    - sudo
  package:
    name: '{{ item }}'
    state: present
  tags:
    - sudo

- name: create group
  loop: '{{ sudo_groups }}'
  group:
    name: '{{ item }}'
    system: yes
    state: present
  tags:
    - sudo

- name: write sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s
  tags:
    - sudo
